<?php
    class VoucherQuery
    {
        function countRecordExist($EMP_AREA_CODE, $EMP_REG_SERIAL_NO, $EMP_SUB_AREA_CODE, $EMP_SUB_SERIAL_NO, $FROM_DATE, $TO_DATE)
        {
            $QUERY = "SELECT count(*) count FROM CB_VOUCHER WHERE EMP_AREA_CODE = '$EMP_AREA_CODE' and 
            EMP_REG_SERIAL_NO = '$EMP_REG_SERIAL_NO' and EMP_SUB_AREA_CODE = '$EMP_SUB_AREA_CODE'
            and EMP_SUB_SERIAL_NO = $EMP_SUB_SERIAL_NO and FROM_DATE = '$FROM_DATE' and TO_DATE = '$TO_DATE'";

            return $QUERY;
        }
        function getVoucherNumber()
        {
            $QUERY = "SELECT max(PMT_SLIP_NO) VOUCHER_NO FROM CB_VOUCHER";
            return $QUERY;
        }
        function getEmpName($EMP_AREA_CODE, $EMP_REG_SERIAL_NO, $EMP_SUB_AREA_CODE, $EMP_SUB_SERIAL_NO)
        {
            $QUERY = "SELECT NAME_OF_ESTABLISHMENT FROM CB_EMPLOYER 
            WHERE EMP_AREA_CODE = '$EMP_AREA_CODE' 
            and emp_reg_serial_no = lpad('$EMP_REG_SERIAL_NO',5, '0')
            and EMP_SUB_AREA_CODE = '$EMP_SUB_AREA_CODE'
            and EMP_SUB_SERIAL_NO = $EMP_SUB_SERIAL_NO
            ";
            return $QUERY;
        }
        function InsertintoCBVoucherCurrent($PMT_SLIP_NO, $EMP_AREA_CODE, $EMP_REG_SERIAL_NO, 
        $EMP_SUB_AREA_CODE, $EMP_SUB_SERIAL_NO, $CURRENT_MONTH_PA, $FROM_DATE, $TO_DATE, 
        $TOTAL_BEFORE_DUE, 
        $SI_AFTER_DUE, $TOTAL_AFTER_DUE, $CREATED_BY, 
        $MODIFIED_BY, $DATE_DUE, $NUMBER_OF_IPS, $MIN_WAGES)
        {
        
            $QUERY = "INSERT INTO CB_VOUCHER (PMT_SLIP_NO, EMP_AREA_CODE, EMP_REG_SERIAL_NO, 
            EMP_SUB_AREA_CODE, EMP_SUB_SERIAL_NO, CURRENT_MONTH_PA, CURRENT_DEMAND_PA, 
            TOTAL_ARREAR_AMOUNT, FROM_DATE, TO_DATE, SI_BEFORE_DUE, TOTAL_BEFORE_DUE, 
            SI_AFTER_DUE, TOTAL_AFTER_DUE, DUE_DATE, PARTIAL_ARREAR_AMOUNT, 
            CUR_MON_AMT_BEFORE_DUE, CUR_MON_AMT_AFTER_DUE, CUR_DMD_AMT_BEFORE_DUE, CUR_DMD_AMT_AFTER_DUE, 
            ARREARS_BEFORE_DUE, ARREARS_AFTER_DUE ,CREATED_BY, CREATED_DATE, 
            MODIFIED_BY , MODIFIED_DATE ,PROCESS_STATUS, GENERATED_FROM, NO_OF_IPS, MIN_WAGES) 
            VALUES ($PMT_SLIP_NO, '$EMP_AREA_CODE', $EMP_REG_SERIAL_NO, '$EMP_SUB_AREA_CODE', 
            $EMP_SUB_SERIAL_NO, $CURRENT_MONTH_PA, 0, 
            0, '$FROM_DATE', '$TO_DATE', 0,
            $TOTAL_BEFORE_DUE, $SI_AFTER_DUE, $TOTAL_AFTER_DUE, $DATE_DUE,0, 
            $TOTAL_BEFORE_DUE, $TOTAL_AFTER_DUE, 0, 0, 
            0,0, '$CREATED_BY', sysdate, '$MODIFIED_BY', 
            sysdate, null, '172.16.0.24', '$NUMBER_OF_IPS', '$MIN_WAGES')";
            
            return $QUERY;
        }

        function InsertintoCBVoucherArrear($PMT_SLIP_NO, $EMP_AREA_CODE, $EMP_REG_SERIAL_NO, $EMP_SUB_AREA_CODE, 
        $EMP_SUB_SERIAL_NO, $FROM_DATE, $TO_DATE, $SI_AFTER_DUE, $TOTAL_AFTER_DUE, $CREATED_BY, 
        $MODIFIED_BY, $DATE_DUE, $NUMBER_OF_IPS)
        {
            $QUERY = "INSERT INTO CB_VOUCHER (PMT_SLIP_NO, EMP_AREA_CODE, EMP_REG_SERIAL_NO, EMP_SUB_AREA_CODE, 
            EMP_SUB_SERIAL_NO, CURRENT_MONTH_PA, CURRENT_DEMAND_PA, TOTAL_ARREAR_AMOUNT, 
            FROM_DATE, TO_DATE, SI_BEFORE_DUE, 
            TOTAL_BEFORE_DUE, SI_AFTER_DUE, TOTAL_AFTER_DUE, DUE_DATE, PARTIAL_ARREAR_AMOUNT, 
            CUR_MON_AMT_BEFORE_DUE, CUR_MON_AMT_AFTER_DUE, CUR_DMD_AMT_BEFORE_DUE, CUR_DMD_AMT_AFTER_DUE, 
            ARREARS_BEFORE_DUE, ARREARS_AFTER_DUE ,CREATED_BY, CREATED_DATE, 
            MODIFIED_BY , MODIFIED_DATE ,PROCESS_STATUS, GENERATED_FROM, NO_OF_IPS) 
            
            VALUES ($PMT_SLIP_NO, '$EMP_AREA_CODE', $EMP_REG_SERIAL_NO, '$EMP_SUB_AREA_CODE', 
            $EMP_SUB_SERIAL_NO, 0, 0, $TOTAL_AFTER_DUE, '$FROM_DATE', '$TO_DATE', 0,$TOTAL_AFTER_DUE, 
            $SI_AFTER_DUE, $TOTAL_AFTER_DUE, $DATE_DUE,0, 0, 0, 0, 0, $TOTAL_AFTER_DUE,
            $TOTAL_AFTER_DUE, '$CREATED_BY', sysdate, '$MODIFIED_BY', sysdate, null, 
            '172.16.0.24', '$NUMBER_OF_IPS')";

            return $QUERY;
        }

        function InsertintoCBVoucherRateDifference($PMT_SLIP_NO, $EMP_AREA_CODE, $EMP_REG_SERIAL_NO, $EMP_SUB_AREA_CODE, 
        $EMP_SUB_SERIAL_NO, $FROM_DATE, $TO_DATE, 
        $SI_AFTER_DUE, $TOTAL_AFTER_DUE, $CREATED_BY, 
        $MODIFIED_BY, $DATE_DUE, $NUMBER_OF_IPS)
        {
            $QUERY = "INSERT INTO CB_VOUCHER (PMT_SLIP_NO, EMP_AREA_CODE, EMP_REG_SERIAL_NO, EMP_SUB_AREA_CODE, 
            EMP_SUB_SERIAL_NO, CURRENT_MONTH_PA, CURRENT_DEMAND_PA, TOTAL_ARREAR_AMOUNT, 
            FROM_DATE, TO_DATE, SI_BEFORE_DUE, 
            TOTAL_BEFORE_DUE, SI_AFTER_DUE, TOTAL_AFTER_DUE, DUE_DATE, PARTIAL_ARREAR_AMOUNT, 
            CUR_MON_AMT_BEFORE_DUE, CUR_MON_AMT_AFTER_DUE, CUR_DMD_AMT_BEFORE_DUE, CUR_DMD_AMT_AFTER_DUE, 
            ARREARS_BEFORE_DUE, ARREARS_AFTER_DUE ,CREATED_BY, CREATED_DATE, 
            MODIFIED_BY , MODIFIED_DATE ,PROCESS_STATUS, GENERATED_FROM, NO_OF_IPS) 
            
            VALUES ($PMT_SLIP_NO, '$EMP_AREA_CODE', $EMP_REG_SERIAL_NO, '$EMP_SUB_AREA_CODE', 
            $EMP_SUB_SERIAL_NO, 0, 0, $TOTAL_AFTER_DUE, '$FROM_DATE', '$TO_DATE', 0,$TOTAL_AFTER_DUE, 
            $SI_AFTER_DUE, $TOTAL_AFTER_DUE, $DATE_DUE,0, 0, 0, 0, 0, $TOTAL_AFTER_DUE,
            $TOTAL_AFTER_DUE, '$CREATED_BY', sysdate, '$MODIFIED_BY', sysdate, null, 
            '172.16.0.24', '$NUMBER_OF_IPS')";

            return $QUERY;
        }

        function InsertintoCBVoucherType($PMT_SLIP_NO, $TYPE, $CREATED_BY, $MODIFIED_BY)
        {
            $QUERY =  "INSERT INTO CB_VOUCHER_TYPE(PMT_SLIP_NO, GENERATION_DATE, STATUS, TYPE, CREATED_BY, CREATED_DATE, 
            MODIFIED_BY, MODIFIED_DATE) 
            VALUES ($PMT_SLIP_NO, sysdate, 'G', '$TYPE', '$CREATED_BY', sysdate, 
            '$MODIFIED_BY', sysdate)";

            return $QUERY;
        }
    }
?>